package witx.surface.psi

import com.intellij.psi.tree.IElementType

object WitxTypes {
    // Tokens
    val LINE_COMMENT: IElementType = WitxTokenType("LINE_COMMENT")
    val BLOCK_COMMENT: IElementType = WitxTokenType("BLOCK_COMMENT")
    val INTEGER: IElementType = WitxTokenType("INTEGER")
    val IDENTIFIER: IElementType = WitxTokenType("IDENTIFIER")
    val STRING_LITERAL: IElementType = WitxTokenType("STRING_LITERAL")
    val STRING_ESCAPE: IElementType = WitxTokenType("STRING_ESCAPE")

    val EQ: IElementType = WitxTokenType("EQ")
    val COLON: IElementType = WitxTokenType("COLON")
    val SEMICOLON: IElementType = WitxTokenType("SEMICOLON")
    val COMMA: IElementType = WitxTokenType("COMMA")
    val DOT: IElementType = WitxTokenType("DOT")
    val AT: IElementType = WitxTokenType("AT")
    val SLASH: IElementType = WitxTokenType("SLASH")
    val STAR: IElementType = WitxTokenType("STAR")
    val ARROW: IElementType = WitxTokenType("ARROW")

    val PAREN_L: IElementType = WitxTokenType("PAREN_L")
    val PAREN_R: IElementType = WitxTokenType("PAREN_R")
    val BRACE_L: IElementType = WitxTokenType("BRACE_L")
    val BRACE_R: IElementType = WitxTokenType("BRACE_R")
    val ANGLE_L: IElementType = WitxTokenType("ANGLE_L")
    val ANGLE_R: IElementType = WitxTokenType("ANGLE_R")

    // Keywords
    val KW_AS: IElementType = WitxTokenType("KW_AS")
    val KW_ASYNC: IElementType = WitxTokenType("KW_ASYNC")
    val KW_BOOL: IElementType = WitxTokenType("KW_BOOL")
    val KW_BORROW: IElementType = WitxTokenType("KW_BORROW")
    val KW_CHAR: IElementType = WitxTokenType("KW_CHAR")
    val KW_CONSTRUCTOR: IElementType = WitxTokenType("KW_CONSTRUCTOR")
    val KW_ENUM: IElementType = WitxTokenType("KW_ENUM")
    val KW_EXPORT: IElementType = WitxTokenType("KW_EXPORT")
    val KW_F32: IElementType = WitxTokenType("KW_F32")
    val KW_F64: IElementType = WitxTokenType("KW_F64")
    val KW_FLAGS: IElementType = WitxTokenType("KW_FLAGS")
    val KW_FROM: IElementType = WitxTokenType("KW_FROM")
    val KW_FUNC: IElementType = WitxTokenType("KW_FUNC")
    val KW_FUTURE: IElementType = WitxTokenType("KW_FUTURE")
    val KW_IMPORT: IElementType = WitxTokenType("KW_IMPORT")
    val KW_INCLUDE: IElementType = WitxTokenType("KW_INCLUDE")
    val KW_INTERFACE: IElementType = WitxTokenType("KW_INTERFACE")
    val KW_LIST: IElementType = WitxTokenType("KW_LIST")
    val KW_MAP: IElementType = WitxTokenType("KW_MAP")
    val KW_OPTION: IElementType = WitxTokenType("KW_OPTION")
    val KW_OWN: IElementType = WitxTokenType("KW_OWN")
    val KW_PACKAGE: IElementType = WitxTokenType("KW_PACKAGE")
    val KW_RECORD: IElementType = WitxTokenType("KW_RECORD")
    val KW_RESOURCE: IElementType = WitxTokenType("KW_RESOURCE")
    val KW_RESULT: IElementType = WitxTokenType("KW_RESULT")
    val KW_S16: IElementType = WitxTokenType("KW_S16")
    val KW_S32: IElementType = WitxTokenType("KW_S32")
    val KW_S64: IElementType = WitxTokenType("KW_S64")
    val KW_S8: IElementType = WitxTokenType("KW_S8")
    val KW_STATIC: IElementType = WitxTokenType("KW_STATIC")
    val KW_STREAM: IElementType = WitxTokenType("KW_STREAM")
    val KW_STRING: IElementType = WitxTokenType("KW_STRING")
    val KW_TUPLE: IElementType = WitxTokenType("KW_TUPLE")
    val KW_TYPE: IElementType = WitxTokenType("KW_TYPE")
    val KW_U16: IElementType = WitxTokenType("KW_U16")
    val KW_U32: IElementType = WitxTokenType("KW_U32")
    val KW_U64: IElementType = WitxTokenType("KW_U64")
    val KW_U8: IElementType = WitxTokenType("KW_U8")
    val KW_USE: IElementType = WitxTokenType("KW_USE")
    val KW_VARIANT: IElementType = WitxTokenType("KW_VARIANT")
    val KW_WITH: IElementType = WitxTokenType("KW_WITH")
    val KW_WORLD: IElementType = WitxTokenType("KW_WORLD")
    val KW_EXTEND: IElementType = WitxTokenType("KW_EXTEND")

    // Composite elements
    val FILE: IElementType = WitxElementType("FILE")
    val PACKAGE_DECL: IElementType = WitxElementType("PACKAGE_DECL")
    val PACKAGE_NAME: IElementType = WitxElementType("PACKAGE_NAME")
    val INTERFACE_DECL: IElementType = WitxElementType("INTERFACE_DECL")
    val WORLD_DECL: IElementType = WitxElementType("WORLD_DECL")
    val USE_DECL: IElementType = WitxElementType("USE_DECL")
    val ITEM_DECL: IElementType = WitxElementType("ITEM_DECL")
    val FUNC_DECL: IElementType = WitxElementType("FUNC_DECL")
    val TYPE_DECL: IElementType = WitxElementType("TYPE_DECL")
    val RECORD_DECL: IElementType = WitxElementType("RECORD_DECL")
    val VARIANT_DECL: IElementType = WitxElementType("VARIANT_DECL")
    val ENUM_DECL: IElementType = WitxElementType("ENUM_DECL")
    val FLAGS_DECL: IElementType = WitxElementType("FLAGS_DECL")
    val RESOURCE_DECL: IElementType = WitxElementType("RESOURCE_DECL")
    val IMPORT_DECL: IElementType = WitxElementType("IMPORT_DECL")
    val EXPORT_DECL: IElementType = WitxElementType("EXPORT_DECL")
    val INCLUDE_DECL: IElementType = WitxElementType("INCLUDE_DECL")
    val ATTRIBUTE: IElementType = WitxElementType("ATTRIBUTE")
    val EXTEND_DECL: IElementType = WitxElementType("EXTEND_DECL")
}
