pluginGroup=WIT
pluginName=intellij-wit
pluginVersion=0.1.4

platformVersion=2026.1
pluginSinceBuild=261

platformPlugins=PsiViewer:253.7181
platformBundledPlugins=com.intellij.java,com.intellij.modules.ultimate,com.intellij.modules.json

pluginRepositoryUrl=https://github.com/oovm/intellij-plugins
