package jss.surface.psi

import com.intellij.lang.ASTNode
import com.intellij.psi.PsiElement
import com.intellij.psi.tree.IElementType

object JssTypes {
    @JvmField val ANNOTATION: IElementType = JssElementType("ANNOTATION")
    @JvmField val ANNOTATION_BLOCK: IElementType = JssElementType("ANNOTATION_BLOCK")
    @JvmField val ANNOTATION_ONE: IElementType = JssElementType("ANNOTATION_ONE")
    @JvmField val ARRAY: IElementType = JssElementType("ARRAY")
    @JvmField val BOOLEAN: IElementType = JssElementType("BOOLEAN")
    @JvmField val BRACE_BLOCK: IElementType = JssElementType("BRACE_BLOCK")
    @JvmField val BRACKET_BLOCK: IElementType = JssElementType("BRACKET_BLOCK")
    @JvmField val CLASS_BLOCK: IElementType = JssElementType("CLASS_BLOCK")
    @JvmField val CLASS_BOUND: IElementType = JssElementType("CLASS_BOUND")
    @JvmField val CLASS_FIELD: IElementType = JssElementType("CLASS_FIELD")
    @JvmField val CLASS_STATEMENT: IElementType = JssElementType("CLASS_STATEMENT")
    @JvmField val COMPARE: IElementType = JssElementType("COMPARE")
    @JvmField val IDENTIFIER: IElementType = JssElementType("IDENTIFIER")
    @JvmField val INTEGER_SIGNED: IElementType = JssElementType("INTEGER_SIGNED")
    @JvmField val KEY: IElementType = JssElementType("KEY")
    @JvmField val KV_PAIR: IElementType = JssElementType("KV_PAIR")
    @JvmField val LET_STATEMENT: IElementType = JssElementType("LET_STATEMENT")
    @JvmField val MODIFIERS: IElementType = JssElementType("MODIFIERS")
    @JvmField val NAMESPACE: IElementType = JssElementType("NAMESPACE")
    @JvmField val NAMESPACE_STATEMENT: IElementType = JssElementType("NAMESPACE_STATEMENT")
    @JvmField val NULL: IElementType = JssElementType("NULL")
    @JvmField val OBJECT: IElementType = JssElementType("OBJECT")
    @JvmField val SCHEMA: IElementType = JssElementType("SCHEMA")
    @JvmField val SCHEMA_STATEMENT: IElementType = JssElementType("SCHEMA_STATEMENT")
    @JvmField val SET: IElementType = JssElementType("SET")
    @JvmField val STRING_LITERAL: IElementType = JssElementType("STRING_LITERAL")
    @JvmField val TYPE_EXPRESSION: IElementType = JssElementType("TYPE_EXPRESSION")
    @JvmField val TYPE_GENERIC: IElementType = JssElementType("TYPE_GENERIC")
    @JvmField val TYPE_GENERIC_BOUND: IElementType = JssElementType("TYPE_GENERIC_BOUND")
    @JvmField val TYPE_GENERIC_COMPARE: IElementType = JssElementType("TYPE_GENERIC_COMPARE")
    @JvmField val TYPE_GENERIC_RANGE: IElementType = JssElementType("TYPE_GENERIC_RANGE")
    @JvmField val TYPE_NUMBER: IElementType = JssElementType("TYPE_NUMBER")
    @JvmField val TYPE_SYMBOL: IElementType = JssElementType("TYPE_SYMBOL")
    @JvmField val UNION_BLOCK: IElementType = JssElementType("UNION_BLOCK")
    @JvmField val UNION_FIELD: IElementType = JssElementType("UNION_FIELD")
    @JvmField val UNION_INNER: IElementType = JssElementType("UNION_INNER")
    @JvmField val UNION_STATEMENT: IElementType = JssElementType("UNION_STATEMENT")
    @JvmField val URL_MAYBE_VALID: IElementType = JssElementType("URL_MAYBE_VALID")
    @JvmField val VALUE: IElementType = JssElementType("VALUE")

    @JvmField val ACCENT: IElementType = JssTokenType("^")
    @JvmField val ANGLE_L: IElementType = JssTokenType("<")
    @JvmField val ANGLE_R: IElementType = JssTokenType(">")
    @JvmField val ANNOTATION_MARK: IElementType = JssTokenType("#")
    @JvmField val BRACE_L: IElementType = JssTokenType("{")
    @JvmField val BRACE_R: IElementType = JssTokenType("}")
    @JvmField val BRACKET_L: IElementType = JssTokenType("[")
    @JvmField val BRACKET_R: IElementType = JssTokenType("]")
    @JvmField val BYTE: IElementType = JssTokenType("Byte")
    @JvmField val CHARACTER: IElementType = JssTokenType("CHARACTER")
    @JvmField val COLON: IElementType = JssTokenType(":")
    @JvmField val COMMA: IElementType = JssTokenType(",")
    @JvmField val COMMENT: IElementType = JssTokenType("DocumentInline")
    @JvmField val COMMENT_BLOCK: IElementType = JssTokenType("DocumentBlock")
    @JvmField val COMMENT_DOCUMENT: IElementType = JssTokenType("DocumentComment")
    @JvmField val DECIMAL: IElementType = JssTokenType("Decimal")
    @JvmField val DOLLAR: IElementType = JssTokenType("$")
    @JvmField val DOT: IElementType = JssTokenType(".")
    @JvmField val EQ: IElementType = JssTokenType("=")
    @JvmField val ESCAPE_SPECIAL: IElementType = JssTokenType("ESCAPE_SPECIAL")
    @JvmField val ESCAPE_UNICODE: IElementType = JssTokenType("ESCAPE_UNICODE")
    @JvmField val GEQ: IElementType = JssTokenType(">=")
    @JvmField val INTEGER: IElementType = JssTokenType("Integer")
    @JvmField val KW_CLASS: IElementType = JssTokenType("class")
    @JvmField val KW_DEFINE: IElementType = JssTokenType("function")
    @JvmField val KW_LET: IElementType = JssTokenType("let")
    @JvmField val KW_NAMESPACE: IElementType = JssTokenType("namespace")
    @JvmField val KW_UNION: IElementType = JssTokenType("union")
    @JvmField val LEQ: IElementType = JssTokenType("<=")
    @JvmField val PARENTHESIS_L: IElementType = JssTokenType("(")
    @JvmField val PARENTHESIS_R: IElementType = JssTokenType(")")
    @JvmField val RANGE_EQ: IElementType = JssTokenType("..=")
    @JvmField val RANGE_LE: IElementType = JssTokenType("..<")
    @JvmField val SEMICOLON: IElementType = JssTokenType(";")
    @JvmField val SIGN: IElementType = JssTokenType("SIGN")
    @JvmField val STAR: IElementType = JssTokenType("*")
    @JvmField val STRING: IElementType = JssTokenType("String")
    @JvmField val STRING_DQ: IElementType = JssTokenType("STRING_DQ")
    @JvmField val STRING_SQ: IElementType = JssTokenType("STRING_SQ")
    @JvmField val SYMBOL: IElementType = JssTokenType("Symbol")
    @JvmField val URL: IElementType = JssTokenType("Url")

    object Factory {
        @JvmStatic
        fun createElement(node: ASTNode): PsiElement = when (node.elementType) {
            ANNOTATION -> VosAnnotationNode(node)
            ANNOTATION_BLOCK -> VosAnnotationBlockNode(node)
            ANNOTATION_ONE -> VosAnnotationOneNode(node)
            ARRAY -> JssArrayNode(node)
            BOOLEAN -> VosBooleanNode(node)
            BRACE_BLOCK -> JssBraceBlockNode(node)
            BRACKET_BLOCK -> JssBracketBlockNode(node)
            CLASS_BLOCK -> JssClassBlockNode(node)
            CLASS_BOUND -> VosClassBoundNode(node)
            CLASS_FIELD -> VosClassFieldNode(node)
            CLASS_STATEMENT -> VosClassStatementNode(node)
            COMPARE -> VosCompareNode(node)
            IDENTIFIER -> VosIdentifierNode(node)
            INTEGER_SIGNED -> VosIntegerSignedNode(node)
            KEY -> VosKeyNode(node)
            KV_PAIR -> JssKvPairNode(node)
            LET_STATEMENT -> VosLetStatementNode(node)
            MODIFIERS -> VosModifiersNode(node)
            NAMESPACE -> VosNamespaceNode(node)
            NAMESPACE_STATEMENT -> VosNamespaceStatementNode(node)
            NULL -> VosNullNode(node)
            OBJECT -> JssObjectNode(node)
            SCHEMA -> VosSchemaNode(node)
            SCHEMA_STATEMENT -> JssSchemaStatementNode(node)
            SET -> VosSetNode(node)
            STRING_LITERAL -> VosStringLiteralNode(node)
            TYPE_EXPRESSION -> JssTypeExpressionNode(node)
            TYPE_GENERIC -> VosTypeGenericNode(node)
            TYPE_GENERIC_BOUND -> VosTypeGenericBoundNode(node)
            TYPE_GENERIC_COMPARE -> VosTypeGenericCompareNode(node)
            TYPE_GENERIC_RANGE -> VosTypeGenericRangeNode(node)
            TYPE_NUMBER -> VosTypeNumberNode(node)
            TYPE_SYMBOL -> JssTypeSymbolNode(node)
            UNION_BLOCK -> JssUnionBlockNode(node)
            UNION_FIELD -> VosUnionFieldNode(node)
            UNION_INNER -> VosUnionInnerNode(node)
            UNION_STATEMENT -> VosUnionStatementNode(node)
            URL_MAYBE_VALID -> VosUrlMaybeValidNode(node)
            VALUE -> VosValueNode(node)
            else -> VosNode(node)
        }
    }
}
